import {mkdir,writeFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
const url=process.env.MODEL_URL;
const expected=process.env.MODEL_SHA256||'9a65654d5de83f73201f9577b3fb44478d7ef6d0412b81c2467724a4de1151f5';
const required=['blink_L','blink_R','browUp_L','browUp_R','jawOpen','mouthOpen','mouthSmile_L','mouthSmile_R','mouthPucker','mouthFunnel','mouthClose'];
if(!url)throw new Error('MODEL_URL is required to materialize the canonical GLB in CI');
await mkdir('public/assets/model',{recursive:true});
const response=await fetch(url);if(!response.ok)throw new Error(`MODEL_DOWNLOAD_FAILED:${response.status}`);
const data=Buffer.from(await response.arrayBuffer());
const sha=createHash('sha256').update(data).digest('hex');
if(sha!==expected)throw new Error(`MODEL_SHA256_MISMATCH expected=${expected} actual=${sha}`);
if(data.length!==43580292)throw new Error(`MODEL_SIZE_MISMATCH expected=43580292 actual=${data.length}`);
const v=new DataView(data.buffer,data.byteOffset,data.byteLength);if(v.getUint32(0,true)!==0x46546c67||v.getUint32(4,true)!==2)throw new Error('MODEL_NOT_GLB2');
const jsonLength=v.getUint32(12,true),jsonType=v.getUint32(16,true);if(jsonType!==0x4e4f534a)throw new Error('MODEL_JSON_CHUNK_MISSING');
const json=JSON.parse(new TextDecoder().decode(data.subarray(20,20+jsonLength)));
const names=(json.meshes||[]).flatMap(m=>m.extras?.targetNames||[]);const missing=required.filter(x=>!names.includes(x));
if(missing.length)throw new Error(`MODEL_MORPHS_MISSING:${missing.join(',')}`);
await writeFile('public/assets/model/model_base.glb',data);await writeFile('public/assets/model/model_base.glb.sha256',`${sha}  model_base.glb\n`);
console.log(`Canonical Svetlana GLB verified: ${data.length} bytes ${sha}; morphs=${required.length}`);
